---
- name: Install Apache2 and deploy index.html on Debian hosts
  hosts: all
  become: yes
  tasks:
    - name: Ensure the system is Debian-based
      fail:
        msg: "This playbook only supports Debian-based systems."
      when: ansible_os_family != "Debian"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        src: /home/ben/work/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
